package entity;
// Generated Apr 25, 2018 10:57:11 AM by Hibernate Tools 4.3.1



/**
 * Satistics generated by hbm2java
 */
public class Satistics  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int match;
     private int wickets;
     private int runs;

    public Satistics() {
    }

    public Satistics(String name, int match, int wickets, int runs) {
       this.name = name;
       this.match = match;
       this.wickets = wickets;
       this.runs = runs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getMatch() {
        return this.match;
    }
    
    public void setMatch(int match) {
        this.match = match;
    }
    public int getWickets() {
        return this.wickets;
    }
    
    public void setWickets(int wickets) {
        this.wickets = wickets;
    }
    public int getRuns() {
        return this.runs;
    }
    
    public void setRuns(int runs) {
        this.runs = runs;
    }




}


