package entity;
// Generated Apr 25, 2018 10:57:11 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String uname;
     private String upass;
     private String email;
     private int phone;

    public Users() {
    }

    public Users(String uname, String upass, String email, int phone) {
       this.uname = uname;
       this.upass = upass;
       this.email = email;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getUpass() {
        return this.upass;
    }
    
    public void setUpass(String upass) {
        this.upass = upass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }




}


